# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:
- script: |
    which java
    java -version
    echo JAVA_HOME_8_X64=$JAVA_HOME_8_X64
    echo JAVA_HOME=$JAVA_HOME
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      mvn deploy:deploy-file 
      -DgroupId=com.example 
      -DartifactId=abc -Dversion=0.0.1 
      -Dpackaging=jar -DrepositoryId=Feed-test -Dfile=C:\abc.jar 
      -Durl=http://172.19.0.6/DefaultCollection/Auto-IOT-Chery/_packaging/Feed-test/maven/v1
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/rockwelladmin/myagent/_work/1/s/target/helloworld.war'
    ArtifactName: 'helloworld'
    publishLocation: 'Container'