# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: CmdLine@2
  inputs:
    script: |
      mvn deploy:deploy-file -DgroupId=helloworld -DartifactId=helloworld -Dversion=1.0-SNAPSHOT -Dpackaging=war -DrepositoryId=Feed-test -Dfile=/home/rockwelladmin/myagent/_work/5/s/target/helloworld.war -Durl=http://172.19.0.6/DefaultCollection/Auto-IOT-Chery/_packaging/Feed-test/maven/v1
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/rockwelladmin/myagent/_work/5/s/target/helloworld.war'
    ArtifactName: 'drop'
    publishLocation: 'Container'