# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:
- script: |
    which java
    java -version
    echo JAVA_HOME_8_X64=$JAVA_HOME_8_X64
    echo JAVA_HOME=$JAVA_HOME


- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      mvn deploy:deploy-file -DgroupId=helloworld -DartifactId=helloworld -Dversion=2.0 -Dpackaging=war -DrepositoryId=Feed-test -Dfile=/home/rockwelladmin/myagent/_work/1/s/target/helloworld.war -Durl=http://172.19.0.6/DefaultCollection/Auto-IOT-Chery/_packaging/Feed-test/maven/v1
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/rockwelladmin/myagent/_work/1/s/target/helloworld.war'
    ArtifactName: 'helloworld'
    publishLocation: 'Container'